import { Button, cn } from '@salon-spa-saas/ui';
import {
  Award,
  BarChart3,
  Building2,
  Calendar,
  CheckCircle2,
  ChevronRight,
  CreditCard,
  Crown,
  DollarSign,
  Download,
  ExternalLink,
  Filter,
  Percent,
  QrCode,
  RefreshCw,
  Scissors,
  ShoppingBag,
  TrendingUp,
  Wallet,
} from 'lucide-react';
import React, { useState } from 'react';
import { UniversalExportModal } from './UniversalExportModal';

export interface RevenueAnalyticsTabProps {
  defaultBranch?: string;
  lockBranch?: boolean;
}

export function RevenueAnalyticsTab({
  defaultBranch = 'Atelier Indrapuri Flagship',
  lockBranch = false,
}: RevenueAnalyticsTabProps = {}) {
  const [selectedBranch, setSelectedBranch] = useState(defaultBranch);
  const [selectedDateRange, setSelectedDateRange] = useState('Current Quarter');
  const [isExportOpen, setIsExportOpen] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  // 9 Revenue Measure KPI Cards (Section 3 PRD)
  const revenueKpis = [
    {
      title: 'Total Gross GMV',
      value: lockBranch ? '₹38,50,000' : '₹1,42,80,000',
      sub: lockBranch ? `Generated by ${defaultBranch}` : 'Gross Turnover',
      icon: TrendingUp,
      color: 'text-teal-600',
      bg: 'bg-teal-50',
    },
    {
      title: 'Services Revenue',
      value: lockBranch ? '₹26,80,000' : '₹98,20,000',
      sub: '69.6% of GMV',
      icon: Scissors,
      color: 'text-[#5A2EA6]',
      bg: 'bg-purple-50',
    },
    {
      title: 'Retail Product Sales',
      value: lockBranch ? '₹5,20,000' : '₹18,40,000',
      sub: '13.5% of GMV',
      icon: ShoppingBag,
      color: 'text-blue-600',
      bg: 'bg-blue-50',
    },
    {
      title: 'Package Sales',
      value: lockBranch ? '₹4,10,000' : '₹14,80,000',
      sub: '10.6% Advance',
      icon: Award,
      color: 'text-indigo-600',
      bg: 'bg-indigo-50',
    },
    {
      title: 'Membership Subscriptions',
      value: lockBranch ? '₹2,40,000' : '₹10,60,000',
      sub: '6.2% Recurring',
      icon: Crown,
      color: 'text-amber-600',
      bg: 'bg-amber-50',
    },
    {
      title: 'Commercial Discounts',
      value: lockBranch ? '-₹2,10,000' : '-₹8,20,000',
      sub: '5.4% Promo Deduct',
      icon: Percent,
      color: 'text-rose-600',
      bg: 'bg-rose-50',
    },
    {
      title: 'Customer Refunds',
      value: lockBranch ? '-₹40,000' : '-₹1,80,000',
      sub: '1.0% Processing',
      icon: RefreshCw,
      color: 'text-red-600',
      bg: 'bg-red-50',
    },
    {
      title: 'GST Tax Accrual (18%)',
      value: lockBranch ? '₹5,22,000' : '₹19,40,000',
      sub: 'Statutory Filing',
      icon: DollarSign,
      color: 'text-slate-700',
      bg: 'bg-slate-100',
    },
    {
      title: 'Net Network Revenue',
      value: lockBranch ? '₹36,00,000' : '₹1,32,80,000',
      sub: 'After Promo/Refunds',
      icon: TrendingUp,
      color: 'text-emerald-700',
      bg: 'bg-emerald-50',
    },
  ];

  // Branch Revenue Matrix (Section 3 PRD)
  const branchRevenues = [
    {
      branch: 'Indore - Vijay Nagar Flagship',
      serviceRev: '₹26,80,000',
      retailRev: '₹5,20,000',
      packageRev: '₹4,10,000',
      memberRev: '₹2,40,000',
      grossRev: '₹38,50,000',
      discounts: '-₹2,10,000',
      refunds: '-₹40,000',
      netRev: '₹36,00,000',
    },
    {
      branch: 'Bhopal - Arera Colony Lounge',
      serviceRev: '₹19,80,000',
      retailRev: '₹3,90,000',
      packageRev: '₹2,90,000',
      memberRev: '₹1,80,000',
      grossRev: '₹28,40,000',
      discounts: '-₹1,60,000',
      refunds: '-₹35,000',
      netRev: '₹26,45,000',
    },
    {
      branch: 'Indore - Palasia Premium Studio',
      serviceRev: '₹18,40,000',
      retailRev: '₹3,60,000',
      packageRev: '₹2,80,000',
      memberRev: '₹2,00,000',
      grossRev: '₹26,80,000',
      discounts: '-₹1,50,000',
      refunds: '-₹30,000',
      netRev: '₹25,00,000',
    },
    {
      branch: 'Ujjain - Freeganj Main Studio',
      serviceRev: '₹15,20,000',
      retailRev: '₹2,60,000',
      packageRev: '₹2,10,000',
      memberRev: '₹1,30,000',
      grossRev: '₹21,20,000',
      discounts: '-₹1,20,000',
      refunds: '-₹25,000',
      netRev: '₹19,75,000',
    },
    {
      branch: 'Gwalior - City Centre Hub',
      serviceRev: '₹11,80,000',
      retailRev: '₹2,20,000',
      packageRev: '₹1,90,000',
      memberRev: '₹1,20,000',
      grossRev: '₹17,10,000',
      discounts: '-₹1,00,000',
      refunds: '-₹20,000',
      netRev: '₹15,90,000',
    },
    {
      branch: 'Jabalpur - Civil Lines Lounge',
      serviceRev: '₹6,20,000',
      retailRev: '₹90,000',
      packageRev: '₹1,00,000',
      memberRev: '₹60,000',
      grossRev: '₹8,70,000',
      discounts: '-₹50,000',
      refunds: '-₹10,000',
      netRev: '₹8,10,000',
    },
  ];

  return (
    <div className="space-y-6">
      {/* Toast */}
      {toastMessage && (
        <div className="fixed bottom-6 right-6 z-50 bg-[#2D1552] text-white px-4 py-3 rounded-xl shadow-xl flex items-center gap-2 border border-purple-400/30 text-xs font-semibold animate-in slide-in-from-bottom-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Export Modal */}
      <UniversalExportModal
        isOpen={isExportOpen}
        onClose={() => setIsExportOpen(false)}
        reportTitle="Revenue & Sales Performance Analytics"
        defaultCategory="Financial"
        availableColumns={[
          'Branch Location',
          'Service Revenue (₹)',
          'Retail Product Sales (₹)',
          'Package Sales (₹)',
          'Membership Sales (₹)',
          'Gross Revenue (₹)',
          'Discounts & Promotions (₹)',
          'Refunds (₹)',
          'Net Network Revenue (₹)',
        ]}
        onExportComplete={(fmt, title) =>
          showToast(`Successfully exported ${title} in ${fmt} format.`)
        }
      />

      {/* 1. Global Filter Bar & Export Actions */}
      <div className="bg-white rounded-2xl p-4 border border-[#5A2EA6]/15 shadow-xs flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-2.5 flex-1">
          {/* Branch Scope */}
          {!lockBranch && (
            <div className="flex items-center gap-1.5 bg-[#F8F5FF] px-3 py-1.5 rounded-xl border border-[#5A2EA6]/20 text-xs">
              <Building2 className="w-3.5 h-3.5 text-[#5A2EA6]" />
              <select
                value={selectedBranch}
                onChange={(e) => setSelectedBranch(e.target.value)}
                className="bg-transparent border-0 font-bold text-ink outline-none cursor-pointer pr-1"
              >
                <option value="all">All Salon Outlets (6 Branches)</option>
                <option value="indore-vn">Indore - Vijay Nagar Flagship</option>
                <option value="indore-pal">Indore - Palasia Premium</option>
                <option value="bhopal-arera">Bhopal - Arera Colony</option>
                <option value="ujjain-free">Ujjain - Freeganj Studio</option>
                <option value="gwalior-cc">Gwalior - City Centre</option>
              </select>
            </div>
          )}

          {/* Date Range */}
          <div className="flex items-center gap-1.5 bg-[#F8F5FF] px-3 py-1.5 rounded-xl border border-[#5A2EA6]/20 text-xs">
            <Calendar className="w-3.5 h-3.5 text-[#5A2EA6]" />
            <select
              value={selectedDateRange}
              onChange={(e) => setSelectedDateRange(e.target.value)}
              className="bg-transparent border-0 font-bold text-ink outline-none cursor-pointer pr-1"
            >
              <option value="Current Quarter">Current Quarter (Q2 FY26-27)</option>
              <option value="Current Month">Current Month (Aug 2026)</option>
              <option value="Last Month">Last Month (Jul 2026)</option>
              <option value="Financial YTD">Financial YTD (FY26-27)</option>
            </select>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            onClick={() => {
              window.location.href = '/finance?tab=transactions';
            }}
            className="h-[36px] px-3 rounded-xl text-xs font-bold border-[#5A2EA6]/30 text-[#5A2EA6] hover:bg-[#5A2EA6]/5 flex items-center gap-1.5"
          >
            <span>Finance Panel</span>
            <ExternalLink className="w-3.5 h-3.5 text-[#5A2EA6]" />
          </Button>

          <Button
            variant="outline"
            onClick={() => setIsExportOpen(true)}
            className="h-[36px] px-3 rounded-xl text-xs font-bold border-[#5A2EA6]/30 text-[#5A2EA6] hover:bg-[#5A2EA6]/5 flex items-center gap-1.5"
          >
            <Download className="w-3.5 h-3.5 text-[#5A2EA6]" />
            <span>Export Revenue Sheet</span>
          </Button>
        </div>
      </div>

      {/* 2. 9 Revenue Measure KPI Cards (Section 3 PRD) */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-9 gap-3">
        {revenueKpis.map((kpi, idx) => {
          const IconComp = kpi.icon;
          return (
            <div
              key={idx}
              className="bg-white rounded-2xl p-3 border border-[#5A2EA6]/15 shadow-xs flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <div
                    className={cn('w-6 h-6 rounded-lg grid place-items-center', kpi.bg, kpi.color)}
                  >
                    <IconComp className="w-3.5 h-3.5" />
                  </div>
                </div>
                <span className="text-[9px] font-bold text-soft uppercase tracking-wider block">
                  {kpi.title}
                </span>
                <strong className="text-sm font-serif font-bold text-ink mt-0.5 block truncate">
                  {kpi.value}
                </strong>
              </div>
              <div className="mt-1.5 pt-1 border-t border-slate-100 text-[9px] text-muted truncate">
                {kpi.sub}
              </div>
            </div>
          );
        })}
      </div>

      {/* 3. Category, Source & Payment Method Split (Section 3 PRD) */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Breakdown 1: Revenue by Service Category */}
        <div className="bg-white rounded-2xl border border-[#5A2EA6]/15 shadow-xs p-5 space-y-4">
          <div className="border-b border-slate-100 pb-3">
            <h3 className="font-serif font-bold text-ink text-base">Service Category Breakdown</h3>
            <p className="text-[11px] text-muted mt-0.5">
              ₹98.2L total services turnover distributed across ritual streams
            </p>
          </div>

          <div className="space-y-3 pt-1 text-xs">
            <div>
              <div className="flex justify-between mb-1">
                <span className="font-bold text-ink">Hair Dressing &amp; Treatments</span>
                <strong className="text-[#5A2EA6]">₹41,20,000 (42.0%)</strong>
              </div>
              <div className="w-full h-2 rounded-full bg-purple-100 overflow-hidden">
                <div className="h-full bg-[#5A2EA6]" style={{ width: '42%' }} />
              </div>
            </div>

            <div>
              <div className="flex justify-between mb-1">
                <span className="font-bold text-ink">Skincare, Facials &amp; Hydra</span>
                <strong className="text-blue-700">₹27,50,000 (28.0%)</strong>
              </div>
              <div className="w-full h-2 rounded-full bg-blue-100 overflow-hidden">
                <div className="h-full bg-blue-600" style={{ width: '28%' }} />
              </div>
            </div>

            <div>
              <div className="flex justify-between mb-1">
                <span className="font-bold text-ink">Bridal &amp; Makeover Couture</span>
                <strong className="text-amber-700">₹17,65,000 (18.0%)</strong>
              </div>
              <div className="w-full h-2 rounded-full bg-amber-100 overflow-hidden">
                <div className="h-full bg-amber-600" style={{ width: '18%' }} />
              </div>
            </div>

            <div>
              <div className="flex justify-between mb-1">
                <span className="font-bold text-ink">Spa, Aromatherapy &amp; Body</span>
                <strong className="text-teal-700">₹11,85,000 (12.0%)</strong>
              </div>
              <div className="w-full h-2 rounded-full bg-teal-100 overflow-hidden">
                <div className="h-full bg-teal-600" style={{ width: '12%' }} />
              </div>
            </div>
          </div>
        </div>

        {/* Breakdown 2: Revenue by Origin Stream */}
        <div className="bg-white rounded-2xl border border-[#5A2EA6]/15 shadow-xs p-5 space-y-4">
          <div className="border-b border-slate-100 pb-3">
            <h3 className="font-serif font-bold text-ink text-base">Revenue by Origin Source</h3>
            <p className="text-[11px] text-muted mt-0.5">
              Services vs Product Retail vs Prepaid Packages vs Memberships
            </p>
          </div>

          <div className="space-y-3 pt-1 text-xs">
            <div>
              <div className="flex justify-between mb-1">
                <span className="font-bold text-ink">In-Salon Services</span>
                <strong className="text-[#5A2EA6]">₹98,20,000 (68.8%)</strong>
              </div>
              <div className="w-full h-2 rounded-full bg-purple-100 overflow-hidden">
                <div className="h-full bg-[#5A2EA6]" style={{ width: '68.8%' }} />
              </div>
            </div>

            <div>
              <div className="flex justify-between mb-1">
                <span className="font-bold text-ink">Home Care Retail Products</span>
                <strong className="text-indigo-700">₹18,40,000 (12.9%)</strong>
              </div>
              <div className="w-full h-2 rounded-full bg-indigo-100 overflow-hidden">
                <div className="h-full bg-indigo-600" style={{ width: '12.9%' }} />
              </div>
            </div>

            <div>
              <div className="flex justify-between mb-1">
                <span className="font-bold text-ink">Prepaid Treatment Packages</span>
                <strong className="text-emerald-700">₹14,80,000 (10.4%)</strong>
              </div>
              <div className="w-full h-2 rounded-full bg-emerald-100 overflow-hidden">
                <div className="h-full bg-emerald-600" style={{ width: '10.4%' }} />
              </div>
            </div>

            <div>
              <div className="flex justify-between mb-1">
                <span className="font-bold text-ink">Club Membership Subscriptions</span>
                <strong className="text-amber-700">₹10,60,000 (7.4%)</strong>
              </div>
              <div className="w-full h-2 rounded-full bg-amber-100 overflow-hidden">
                <div className="h-full bg-amber-600" style={{ width: '7.4%' }} />
              </div>
            </div>
          </div>
        </div>

        {/* Breakdown 3: Payment Tender Methods */}
        <div className="bg-white rounded-2xl border border-[#5A2EA6]/15 shadow-xs p-5 space-y-4">
          <div className="border-b border-slate-100 pb-3">
            <h3 className="font-serif font-bold text-ink text-base">Payment Tender Distribution</h3>
            <p className="text-[11px] text-muted mt-0.5">
              UPI, Debit/Credit cards, cash and digital wallet split
            </p>
          </div>

          <div className="space-y-3 pt-1 text-xs">
            <div className="p-2.5 rounded-xl bg-purple-50/50 border border-purple-100 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <QrCode className="w-4 h-4 text-[#5A2EA6]" />
                <span className="font-bold text-ink">UPI &amp; QR Codes (54%)</span>
              </div>
              <strong className="font-serif font-bold text-[#5A2EA6]">₹77,11,200</strong>
            </div>

            <div className="p-2.5 rounded-xl bg-blue-50/50 border border-blue-100 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <CreditCard className="w-4 h-4 text-blue-600" />
                <span className="font-bold text-ink">Credit / Debit Cards (28%)</span>
              </div>
              <strong className="font-serif font-bold text-blue-700">₹39,98,400</strong>
            </div>

            <div className="p-2.5 rounded-xl bg-emerald-50/50 border border-emerald-100 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <DollarSign className="w-4 h-4 text-emerald-600" />
                <span className="font-bold text-ink">Cash at Register (10%)</span>
              </div>
              <strong className="font-serif font-bold text-emerald-700">₹14,28,000</strong>
            </div>

            <div className="p-2.5 rounded-xl bg-amber-50/50 border border-amber-100 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Wallet className="w-4 h-4 text-amber-600" />
                <span className="font-bold text-ink">Prepaid Wallet / Loyalty (8%)</span>
              </div>
              <strong className="font-serif font-bold text-amber-700">₹11,42,400</strong>
            </div>
          </div>
        </div>
      </div>

      {/* 4. Branch / Floor Department Revenue Breakdown Table */}
      <div className="bg-white rounded-2xl border border-[#5A2EA6]/15 shadow-xs overflow-hidden">
        <div className="p-4 border-b border-[#5A2EA6]/10 flex flex-wrap items-center justify-between gap-3 bg-[#FCFAFF]">
          <div>
            <div className="flex items-center gap-2">
              <Building2 className="w-4 h-4 text-[#5A2EA6]" />
              <h3 className="font-serif font-bold text-ink text-base">
                {lockBranch
                  ? `${defaultBranch} · Departmental Revenue & Collections Ledger`
                  : 'Multi-Branch Revenue & Financial Ledger'}
              </h3>
              <span className="px-2.5 py-0.5 rounded-full bg-[#5A2EA6]/10 text-[#5A2EA6] text-[10px] font-extrabold">
                {lockBranch ? 'Floor Stream Accounting' : 'PRD Revenue Stream Model'}
              </span>
            </div>
            <p className="text-[11px] text-muted mt-0.5">
              {lockBranch
                ? `Revenue breakdown of services, retail products, packages, memberships, and net revenue for ${defaultBranch}`
                : 'Detailed breakdown of services, retail products, package advances, memberships, discounts, refunds, and net revenue'}
            </p>
          </div>
          <span className="text-xs text-soft font-semibold">
            {lockBranch ? '5 Revenue Centres' : '6 Branches Reporting'}
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full min-w-[1100px] text-left text-xs border-collapse">
            <thead>
              <tr className="bg-[#F8F5FF] border-b border-[#5A2EA6]/10 text-[#5A2EA6] font-bold text-[10px] tracking-wider uppercase whitespace-nowrap">
                <th className="p-3.5 pl-5">
                  {lockBranch ? 'Department / Floor Centre' : 'Salon Branch'}
                </th>
                <th className="p-3.5 text-right">Services</th>
                <th className="p-3.5 text-right">Retail</th>
                <th className="p-3.5 text-right">Packages</th>
                <th className="p-3.5 text-right">Memberships</th>
                <th className="p-3.5 text-right font-bold text-ink">Gross GMV</th>
                <th className="p-3.5 text-right text-rose-700">Discounts</th>
                <th className="p-3.5 text-right text-red-700">Refunds</th>
                <th className="p-3.5 pr-5 text-right font-extrabold text-[#5A2EA6]">Net Revenue</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#5A2EA6]/5 font-medium text-slate-700">
              {(lockBranch
                ? [
                    {
                      branch: 'Hair Design, Coloring & Blowdry Bar',
                      serviceRev: '₹14,20,000',
                      retailRev: '₹2,90,000',
                      packageRev: '₹1,80,000',
                      memberRev: '₹1,10,000',
                      grossRev: '₹20,00,000',
                      discounts: '-₹1,10,000',
                      refunds: '-₹20,000',
                      netRev: '₹18,70,000',
                    },
                    {
                      branch: 'Clinical Skin Aesthetics & Hydra-Facials',
                      serviceRev: '₹6,80,000',
                      retailRev: '₹1,40,000',
                      packageRev: '₹1,20,000',
                      memberRev: '₹60,000',
                      grossRev: '₹10,00,000',
                      discounts: '-₹50,000',
                      refunds: '-₹10,000',
                      netRev: '₹9,40,000',
                    },
                    {
                      branch: 'Spa Sanctuary, Body Polish & Aromatherapy',
                      serviceRev: '₹3,40,000',
                      retailRev: '₹50,000',
                      packageRev: '₹70,000',
                      memberRev: '₹40,000',
                      grossRev: '₹5,00,000',
                      discounts: '-₹30,000',
                      refunds: '-₹5,000',
                      netRev: '₹4,65,000',
                    },
                    {
                      branch: 'Nail Bar, Gel Extensions & Pedicure',
                      serviceRev: '₹1,80,000',
                      retailRev: '₹40,000',
                      packageRev: '₹30,000',
                      memberRev: '₹20,000',
                      grossRev: '₹2,70,000',
                      discounts: '-₹15,000',
                      refunds: '-₹3,000',
                      netRev: '₹2,52,000',
                    },
                    {
                      branch: 'Bridal Couture & VIP Dressing Suite',
                      serviceRev: '₹60,000',
                      retailRev: '₹0',
                      packageRev: '₹10,000',
                      memberRev: '₹10,000',
                      grossRev: '₹80,000',
                      discounts: '-₹5,000',
                      refunds: '-₹2,000',
                      netRev: '₹73,000',
                    },
                  ]
                : branchRevenues
              ).map((br, idx) => (
                <tr key={idx} className="hover:bg-[#5A2EA6]/3 transition-colors">
                  <td className="p-3.5 pl-5 whitespace-nowrap font-bold text-ink">{br.branch}</td>
                  <td className="p-3.5 text-right whitespace-nowrap font-mono text-slate-800">
                    {br.serviceRev}
                  </td>
                  <td className="p-3.5 text-right whitespace-nowrap font-mono text-slate-800">
                    {br.retailRev}
                  </td>
                  <td className="p-3.5 text-right whitespace-nowrap font-mono text-slate-800">
                    {br.packageRev}
                  </td>
                  <td className="p-3.5 text-right whitespace-nowrap font-mono text-slate-800">
                    {br.memberRev}
                  </td>
                  <td className="p-3.5 text-right whitespace-nowrap font-serif font-bold text-slate-900">
                    {br.grossRev}
                  </td>
                  <td className="p-3.5 text-right whitespace-nowrap font-mono text-rose-700 font-semibold">
                    {br.discounts}
                  </td>
                  <td className="p-3.5 text-right whitespace-nowrap font-mono text-red-700 font-semibold">
                    {br.refunds}
                  </td>
                  <td className="p-3.5 pr-5 text-right whitespace-nowrap font-serif font-extrabold text-emerald-700 text-sm">
                    {br.netRev}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
