import { type FullClientRecord } from './ClientProfileDossierModal';

export const initialClients: FullClientRecord[] = [
  {
    id: 'CL-10492',
    firstName: 'Akanksha',
    lastName: 'Sharma',
    fullName: 'Akanksha Sharma',
    mobile: '+91 98260 11420',
    email: 'akanksha.sharma@gmail.com',
    gender: 'Female',
    dob: '14 Sep 1992',
    anniversary: '18 Nov 2018',
    anniversaryOccasion: 'Wedding Anniversary',
    avatarInitials: 'AS',
    avatarUrl:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    accentColor: '#5A2EA6',
    primaryBranch: 'Atelier Indrapuri Flagship',
    primaryBranchId: '6b9ce3d7-b71c-404b-bd09-cfb43af547b2',
    franchiseId: null,
    clientSince: 'Jan 2024',
    status: 'Active',
    segment: 'VIP High Value',
    membershipTier: 'Platinum Luxe Member',
    activePackage: '6-Session Hydra Radiance Bundle',
    totalVisits: 18,
    completedVisits: 17,
    cancelledVisits: 1,
    noShows: 0,
    lastVisit: '12 Aug 2026',
    lifetimeValue: 48500,
    averageVisitValue: 2694,
    walletBalance: 3400,
    loyaltyPoints: 1250,
    rebookingRate: 88,
    preferredStaff: 'Ananya Deshmukh',
    preferredServices: '7-Step Medical Hydra-Facial, Signature Blowout',
    preferredChannel: 'WhatsApp',
    language: 'English, Hindi',
    address: {
      line1: 'B-42, Gulmohar Colony, E-8 Extension',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      pincode: '462039',
      country: 'India',
    },
    household: {
      name: 'Sharma Household',
      members: [
        {
          name: 'Akanksha Sharma',
          relation: 'Self (Primary)',
          mobile: '+91 98260 11420',
          isPrimary: true,
        },
        { name: 'Rohan Sharma', relation: 'Spouse', mobile: '+91 98260 11421' },
        { name: 'Anaya Sharma', relation: 'Child (Minor)', mobile: '—' },
      ],
    },
    appointments: [
      {
        id: 'APT-940',
        date: '28 Aug 2026',
        time: '04:00 PM',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Hydra Radiance Maintenance Facial & LED Therapy',
        staff: 'Ananya Deshmukh',
        status: 'Booked',
        amount: 3800,
        source: 'Online Mobile App',
      },
      {
        id: 'APT-901',
        date: '12 Aug 2026',
        time: '02:30 PM',
        branch: 'Atelier Indrapuri Flagship',
        service: '7-Step Medical Hydra-Facial Rejuvenation',
        staff: 'Ananya Deshmukh',
        status: 'Completed',
        amount: 3800,
        source: 'Online Mobile App',
      },
      {
        id: 'APT-844',
        date: '18 Jul 2026',
        time: '11:00 AM',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Signature Precision Cut & Blowout',
        staff: 'Ananya Deshmukh',
        status: 'Completed',
        amount: 1850,
        source: 'WhatsApp Booking',
      },
      {
        id: 'APT-790',
        date: '22 Jun 2026',
        time: '04:00 PM',
        branch: 'Atelier Koregaon Park Grand',
        service: 'Swedish Aromatherapy Deep Tissue Massage',
        staff: 'Pooja Kashyap',
        status: 'Completed',
        amount: 4500,
        source: 'Front Desk Phone',
      },
    ],
    serviceHistory: [
      {
        id: 'SH-01',
        date: '12 Aug 2026',
        branch: 'Atelier Indrapuri Flagship',
        service: '7-Step Medical Hydra-Facial Rejuvenation',
        staff: 'Ananya Deshmukh',
        amount: 3800,
        packageOrMembership: 'Package Session 4/6',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-02',
        date: '18 Jul 2026',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Signature Precision Cut & Blowout',
        staff: 'Ananya Deshmukh',
        amount: 1850,
        packageOrMembership: 'Platinum Tier 15% Off',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-03',
        date: '22 Jun 2026',
        branch: 'Atelier Koregaon Park Grand',
        service: 'Swedish Aromatherapy Deep Tissue Massage',
        staff: 'Pooja Kashyap',
        amount: 4500,
        packageOrMembership: 'Platinum Tier 15% Off',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-04',
        date: '15 May 2026',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Kérastase Caviar Hair Chronologiste Ritual',
        staff: 'Rohit Verma',
        amount: 5200,
        packageOrMembership: 'A la carte',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-05',
        date: '10 Apr 2026',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Gel Polish Manicure & Organic Rose Pedicure',
        staff: 'Kavita Iyer',
        amount: 2400,
        packageOrMembership: 'A la carte',
        rating: 4,
        status: 'Completed',
      },
    ],
    packages: [
      {
        id: 'PKG-01',
        name: '6-Session Hydra Radiance Bundle',
        purchaseDate: '10 May 2026',
        expiryDate: '10 Nov 2026',
        sessionsPurchased: 6,
        sessionsUsed: 4,
        sessionsRemaining: 2,
        packageValue: 19000,
        remainingValue: 6333,
        status: 'Active',
      },
      {
        id: 'PKG-02',
        name: 'Kérastase Caviar Indulgence Trio',
        purchaseDate: '15 Jan 2026',
        expiryDate: '15 Jul 2026',
        sessionsPurchased: 3,
        sessionsUsed: 3,
        sessionsRemaining: 0,
        packageValue: 14000,
        remainingValue: 0,
        status: 'Fully Redeemed',
      },
    ],
    loyaltyTransactions: [
      {
        id: 'TX-01',
        date: '12 Aug 2026',
        type: 'Earned',
        description: 'Hydra Facial Service Reward Points',
        amountOrPoints: '+190 Pts',
        balance: '1,250 Pts',
      },
      {
        id: 'TX-02',
        date: '18 Jul 2026',
        type: 'Wallet Topup',
        description: 'Razorpay UPI Wallet Reload',
        amountOrPoints: '+₹2,000',
        balance: '₹3,400',
      },
      {
        id: 'TX-03',
        date: '18 Jul 2026',
        type: 'Service Debit',
        description: 'Precision Cut Checkout Payment',
        amountOrPoints: '-₹1,850',
        balance: '₹1,400',
      },
      {
        id: 'TX-04',
        date: '22 Jun 2026',
        type: 'Earned',
        description: 'Aromatherapy Spa Experience Bonus',
        amountOrPoints: '+225 Pts',
        balance: '1,060 Pts',
      },
      {
        id: 'TX-05',
        date: '15 May 2026',
        type: 'Redeemed',
        description: 'Kérastase Retail Product Redemption',
        amountOrPoints: '-500 Pts',
        balance: '835 Pts',
      },
    ],
    feedbacks: [
      {
        id: 'FB-01',
        date: '12 Aug 2026',
        service: '7-Step Medical Hydra-Facial',
        branch: 'Atelier Indrapuri Flagship',
        rating: 5,
        npsType: 'Promoter',
        feedback:
          'Amazing radiant glow! Ananya is truly knowledgeable and gentle with clinical treatments.',
      },
      {
        id: 'FB-02',
        date: '18 Jul 2026',
        service: 'Signature Precision Cut',
        branch: 'Atelier Indrapuri Flagship',
        rating: 5,
        npsType: 'Promoter',
        feedback: 'Hair texture feels incredibly soft and the framing layers are flawless.',
      },
      {
        id: 'FB-03',
        date: '22 Jun 2026',
        service: 'Swedish Aromatherapy Massage',
        branch: 'Atelier Koregaon Park Grand',
        rating: 4,
        npsType: 'Promoter',
        feedback: 'Very relaxing spa room ambience. Therapist Pooja applied ideal pressure.',
      },
    ],
    notes: [
      {
        id: 'NT-01',
        date: '12 Aug 2026',
        author: 'Ananya Deshmukh',
        type: 'Medical / Allergy',
        content:
          'Mild sensitivity to synthetic lavender. Always use cold-pressed chamomile organic calming toner for post-facial misting.',
        isConfidential: true,
      },
      {
        id: 'NT-02',
        date: '18 Jul 2026',
        author: 'Front Desk',
        type: 'Styling Preference',
        content:
          'Prefers quiet sessions without loud music. Enjoys warm herbal green tea with honey upon arrival.',
      },
      {
        id: 'NT-03',
        date: '15 May 2026',
        author: 'Rohit Verma',
        type: 'Consultation',
        content: 'Scalp porosity is medium-high; recommends weekly peptide nourishing serum mask.',
      },
    ],
    photos: [
      {
        id: 'PH-01',
        date: '12 Aug 2026',
        service: 'Hydra-Facial',
        staff: 'Ananya Deshmukh',
        type: 'Before',
        caption: 'Pre-treatment diagnostic pores & T-zone hydration assessment',
        consentGranted: true,
      },
      {
        id: 'PH-02',
        date: '12 Aug 2026',
        service: 'Hydra-Facial',
        staff: 'Ananya Deshmukh',
        type: 'After',
        caption: 'Immediate post-extraction luminescence & skin barrier radiance',
        consentGranted: true,
      },
      {
        id: 'PH-03',
        date: '18 Jul 2026',
        service: 'Precision Cut',
        staff: 'Ananya Deshmukh',
        type: 'After',
        caption: 'Finished French blowout with face-framing curtain bangs',
        consentGranted: true,
      },
    ],
    consent: {
      whatsappConsent: true,
      smsConsent: true,
      emailConsent: true,
      phoneConsent: true,
      pushConsent: true,
      marketingConsent: true,
      photoConsent: true,
      consultationConsent: true,
      dateGranted: '15 Jan 2024',
      lastUpdated: '12 Aug 2026',
    },
    autoCelebrationSettings: {
      birthdayAutoSend: true,
      birthdayLeadDays: 3,
      birthdayChannel: 'whatsapp',
      anniversaryAutoSend: true,
      anniversaryLeadDays: 5,
      anniversaryChannel: 'whatsapp',
    },
  },
  {
    id: 'CL-10493',
    firstName: 'Devendra',
    lastName: 'Singhania',
    fullName: 'Devendra Singhania',
    mobile: '+91 99770 44550',
    email: 'devendra.singhania@indore-ventures.in',
    gender: 'Male',
    dob: '08 Dec 1985',
    anniversary: '15 Jan 2012',
    anniversaryOccasion: 'Wedding Anniversary',
    avatarInitials: 'DS',
    avatarUrl:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    accentColor: '#0D9488',
    primaryBranch: 'Atelier Indrapuri Flagship',
    primaryBranchId: '6b9ce3d7-b71c-404b-bd09-cfb43af547b2',
    franchiseId: null,
    clientSince: 'Apr 2024',
    status: 'Active',
    segment: 'Frequent Visitor',
    membershipTier: 'Gold VIP Member',
    activePackage: '10-Session Executive Grooming Pass',
    totalVisits: 14,
    completedVisits: 14,
    cancelledVisits: 0,
    noShows: 0,
    lastVisit: '10 Aug 2026',
    lifetimeValue: 32400,
    averageVisitValue: 2314,
    walletBalance: 1850,
    loyaltyPoints: 840,
    rebookingRate: 92,
    preferredStaff: 'Sameer Sheikh',
    preferredServices: 'Executive Hot Towel Beard Sculpt, Scalp Detox',
    preferredChannel: 'SMS',
    language: 'Hindi, English',
    address: {
      line1: 'Plot 12, Vijay Nagar Sector B',
      city: 'Indore',
      state: 'Madhya Pradesh',
      pincode: '452010',
      country: 'India',
    },
    household: {
      name: 'Singhania Family',
      members: [
        {
          name: 'Devendra Singhania',
          relation: 'Self (Primary)',
          mobile: '+91 99770 44550',
          isPrimary: true,
        },
        { name: 'Radhika Singhania', relation: 'Spouse', mobile: '+91 99770 44552' },
      ],
    },
    appointments: [
      {
        id: 'APT-922',
        date: '25 Aug 2026',
        time: '06:00 PM',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Executive Hot Towel Beard Sculpt & Charcoal Scalp Scrub',
        staff: 'Sameer Sheikh',
        status: 'Confirmed',
        amount: 1450,
        source: 'Online Mobile App',
      },
      {
        id: 'APT-899',
        date: '10 Aug 2026',
        time: '05:00 PM',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Executive Hot Towel Beard Sculpt & Scalp Polish',
        staff: 'Sameer Sheikh',
        status: 'Completed',
        amount: 1150,
        source: 'Front Desk Phone',
      },
      {
        id: 'APT-812',
        date: '14 Jul 2026',
        time: '04:30 PM',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Men’s Royal Foot Reflexology & Beard Trim',
        staff: 'Sameer Sheikh',
        status: 'Completed',
        amount: 2200,
        source: 'POS Walk-in',
      },
    ],
    serviceHistory: [
      {
        id: 'SH-06',
        date: '10 Aug 2026',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Executive Hot Towel Beard Sculpt',
        staff: 'Sameer Sheikh',
        amount: 1150,
        packageOrMembership: 'Package Session 6/10',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-07',
        date: '14 Jul 2026',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Royal Foot Reflexology & Beard Sculpt',
        staff: 'Sameer Sheikh',
        amount: 2200,
        packageOrMembership: 'Gold Tier 10% Off',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-08',
        date: '18 Jun 2026',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Charcoal Detox Scalp Polish & Haircut',
        staff: 'Sameer Sheikh',
        amount: 1750,
        packageOrMembership: 'Package Session 5/10',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-09',
        date: '20 May 2026',
        branch: 'Atelier Indrapuri Flagship',
        service: 'Executive Hot Towel Beard Sculpt',
        staff: 'Sameer Sheikh',
        amount: 1150,
        packageOrMembership: 'Package Session 4/10',
        rating: 5,
        status: 'Completed',
      },
    ],
    packages: [
      {
        id: 'PKG-03',
        name: '10-Session Executive Grooming Pass',
        purchaseDate: '15 Mar 2026',
        expiryDate: '15 Mar 2027',
        sessionsPurchased: 10,
        sessionsUsed: 6,
        sessionsRemaining: 4,
        packageValue: 11000,
        remainingValue: 4400,
        status: 'Active',
      },
    ],
    loyaltyTransactions: [
      {
        id: 'TX-06',
        date: '10 Aug 2026',
        type: 'Earned',
        description: 'Executive Beard Service Loyalty Credit',
        amountOrPoints: '+55 Pts',
        balance: '840 Pts',
      },
      {
        id: 'TX-07',
        date: '14 Jul 2026',
        type: 'Wallet Topup',
        description: 'NetBanking Prepaid Wallet Top-up',
        amountOrPoints: '+₹3,000',
        balance: '₹3,000',
      },
      {
        id: 'TX-08',
        date: '14 Jul 2026',
        type: 'Service Debit',
        description: 'Reflexology Session Auto-debit',
        amountOrPoints: '-₹2,200',
        balance: '₹800',
      },
      {
        id: 'TX-09',
        date: '18 Jun 2026',
        type: 'Earned',
        description: 'Scalp Polish Treatment Reward',
        amountOrPoints: '+90 Pts',
        balance: '785 Pts',
      },
    ],
    feedbacks: [
      {
        id: 'FB-04',
        date: '10 Aug 2026',
        service: 'Beard Sculpt',
        branch: 'Atelier Indrapuri Flagship',
        rating: 5,
        npsType: 'Promoter',
        feedback:
          'Best hot towel shave in central India. Sameer has mastered the straight-edge razor technique.',
      },
      {
        id: 'FB-05',
        date: '14 Jul 2026',
        service: 'Foot Reflexology',
        branch: 'Atelier Indrapuri Flagship',
        rating: 5,
        npsType: 'Promoter',
        feedback: 'Very therapeutic reflexology after a long travel week.',
      },
    ],
    notes: [
      {
        id: 'NT-04',
        date: '10 Aug 2026',
        author: 'Sameer Sheikh',
        type: 'Styling Preference',
        content:
          'Natural neckline taper without sharp block edges. Use organic eucalyptus & cedarwood shaving balm.',
      },
      {
        id: 'NT-05',
        date: '14 Jul 2026',
        author: 'Sameer Sheikh',
        type: 'Medical / Allergy',
        content: 'Sensitive to heavy menthol aftershaves. Prefers soothing aloe vera gel.',
      },
    ],
    photos: [
      {
        id: 'PH-04',
        date: '10 Aug 2026',
        service: 'Beard Sculpt',
        staff: 'Sameer Sheikh',
        type: 'After',
        caption: 'Sharp angular jawline sculpting and crisp moustache blend',
        consentGranted: true,
      },
    ],
    consent: {
      whatsappConsent: true,
      smsConsent: true,
      emailConsent: false,
      phoneConsent: true,
      pushConsent: true,
      marketingConsent: true,
      photoConsent: true,
      consultationConsent: true,
      dateGranted: '12 Apr 2024',
      lastUpdated: '10 Aug 2026',
    },
    autoCelebrationSettings: {
      birthdayAutoSend: true,
      birthdayLeadDays: 2,
      birthdayChannel: 'sms',
      anniversaryAutoSend: true,
      anniversaryLeadDays: 3,
      anniversaryChannel: 'sms',
    },
  },
  {
    id: 'CL-10494',
    firstName: 'Meera',
    lastName: 'Kulkarni',
    fullName: 'Meera Kulkarni',
    mobile: '+91 91234 88770',
    email: 'meera.kulkarni@techpune.com',
    gender: 'Female',
    dob: '22 May 1996',
    anniversary: '04 Dec 2021',
    anniversaryOccasion: 'Wedding Anniversary',
    avatarInitials: 'MK',
    avatarUrl:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    accentColor: '#E11D48',
    primaryBranch: 'Atelier Koregaon Park Grand',
    primaryBranchId: '22983161-1cc6-4ef3-a39f-97bc9af2cdb4',
    franchiseId: 'f2e9206f-653e-48f5-90b1-f5cca50cc92d',
    clientSince: 'Nov 2024',
    status: 'Active',
    segment: 'Membership Client',
    membershipTier: 'Platinum Luxe Member',
    activePackage: 'Balayage & Hair Care Trilogy',
    totalVisits: 11,
    completedVisits: 10,
    cancelledVisits: 1,
    noShows: 0,
    lastVisit: '04 Aug 2026',
    lifetimeValue: 42000,
    averageVisitValue: 3818,
    walletBalance: 5100,
    loyaltyPoints: 1600,
    rebookingRate: 85,
    preferredStaff: 'Rohit Verma',
    preferredServices: 'Balayage Highlight & Tone, Keratin Therapy',
    preferredChannel: 'WhatsApp',
    language: 'English, Marathi',
    address: {
      line1: 'Flat 402, Ganga Carnation, Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      country: 'India',
    },
    household: {
      name: 'Kulkarni Residence',
      members: [
        {
          name: 'Meera Kulkarni',
          relation: 'Self (Primary)',
          mobile: '+91 91234 88770',
          isPrimary: true,
        },
        { name: 'Aditya Kulkarni', relation: 'Spouse', mobile: '+91 91234 88772' },
        { name: 'Suniti Kulkarni', relation: 'Mother-in-Law', mobile: '+91 91234 88775' },
      ],
    },
    appointments: [
      {
        id: 'APT-931',
        date: '30 Aug 2026',
        time: '11:30 AM',
        branch: 'Atelier Koregaon Park Grand',
        service: 'French Gloss Color Glaze & Olaplex Treatment',
        staff: 'Rohit Verma',
        status: 'Booked',
        amount: 4800,
        source: 'WhatsApp Booking',
      },
      {
        id: 'APT-882',
        date: '04 Aug 2026',
        time: '02:00 PM',
        branch: 'Atelier Koregaon Park Grand',
        service: 'Custom Balayage Hair Painting & Gloss Toner',
        staff: 'Rohit Verma',
        status: 'Completed',
        amount: 8500,
        source: 'Online Mobile App',
      },
      {
        id: 'APT-820',
        date: '02 Jul 2026',
        time: '03:00 PM',
        branch: 'Atelier Koregaon Park Grand',
        service: 'Sculpted Gel Extension Refill & Nail Art',
        staff: 'Kavita Iyer',
        status: 'Completed',
        amount: 2600,
        source: 'POS Walk-in',
      },
    ],
    serviceHistory: [
      {
        id: 'SH-10',
        date: '04 Aug 2026',
        branch: 'Atelier Koregaon Park Grand',
        service: 'Custom Balayage Hair Painting & Gloss Toner',
        staff: 'Rohit Verma',
        amount: 8500,
        packageOrMembership: 'Package Session 2/3',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-11',
        date: '02 Jul 2026',
        branch: 'Atelier Koregaon Park Grand',
        service: 'Sculpted Gel Extension Refill & French Ombre',
        staff: 'Kavita Iyer',
        amount: 2600,
        packageOrMembership: 'Platinum Tier 15% Off',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-12',
        date: '18 May 2026',
        branch: 'Atelier Koregaon Park Grand',
        service: 'Brazilian Blowout Keratin Smoothing Infusion',
        staff: 'Rohit Verma',
        amount: 7200,
        packageOrMembership: 'Package Session 1/3',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-13',
        date: '05 Apr 2026',
        branch: 'Atelier Koregaon Park Grand',
        service: 'Ayurvedic Kumkumadi Radiance Face Ritual',
        staff: 'Ananya Deshmukh',
        amount: 3500,
        packageOrMembership: 'Platinum Tier 15% Off',
        rating: 4,
        status: 'Completed',
      },
    ],
    packages: [
      {
        id: 'PKG-04',
        name: 'Balayage & Hair Care Trilogy',
        purchaseDate: '10 May 2026',
        expiryDate: '10 Nov 2026',
        sessionsPurchased: 3,
        sessionsUsed: 2,
        sessionsRemaining: 1,
        packageValue: 19500,
        remainingValue: 6500,
        status: 'Active',
      },
      {
        id: 'PKG-05',
        name: '6-Session Gel Overlay & Nail Art',
        purchaseDate: '01 Jan 2026',
        expiryDate: '01 Jul 2026',
        sessionsPurchased: 6,
        sessionsUsed: 5,
        sessionsRemaining: 1,
        packageValue: 12000,
        remainingValue: 2000,
        status: 'Active',
      },
    ],
    loyaltyTransactions: [
      {
        id: 'TX-10',
        date: '04 Aug 2026',
        type: 'Earned',
        description: 'Balayage Service Platinum Bonus Points',
        amountOrPoints: '+425 Pts',
        balance: '1,600 Pts',
      },
      {
        id: 'TX-11',
        date: '04 Aug 2026',
        type: 'Wallet Topup',
        description: 'Corporate Card Wallet Top-up',
        amountOrPoints: '+₹6,000',
        balance: '₹6,000',
      },
      {
        id: 'TX-12',
        date: '04 Aug 2026',
        type: 'Service Debit',
        description: 'Balayage Add-on Olaplex Charge',
        amountOrPoints: '-₹900',
        balance: '₹5,100',
      },
      {
        id: 'TX-13',
        date: '02 Jul 2026',
        type: 'Earned',
        description: 'Gel Extension Loyalty Accrual',
        amountOrPoints: '+130 Pts',
        balance: '1,175 Pts',
      },
    ],
    feedbacks: [
      {
        id: 'FB-06',
        date: '04 Aug 2026',
        service: 'Balayage Highlight & Tone',
        branch: 'Atelier Koregaon Park Grand',
        rating: 5,
        npsType: 'Promoter',
        feedback:
          'Rohit created the exact champagne blonde balayage I envisioned without any brassiness. Outstanding!',
      },
      {
        id: 'FB-07',
        date: '02 Jul 2026',
        service: 'Sculpted Gel Extensions',
        branch: 'Atelier Koregaon Park Grand',
        rating: 4,
        npsType: 'Promoter',
        feedback: 'Nails lasted over 4 weeks without lifting.',
      },
    ],
    notes: [
      {
        id: 'NT-06',
        date: '04 Aug 2026',
        author: 'Rohit Verma',
        type: 'Consultation',
        content:
          'Color Formulation: Majirel 6.1 (Ash Dark Blonde) + 7.1 with 20 Vol developer for soft root shadow blend. Dialight 9.02 for gloss toner.',
        isConfidential: true,
      },
      {
        id: 'NT-07',
        date: '04 Aug 2026',
        author: 'Rohit Verma',
        type: 'Medical / Allergy',
        content:
          'Slight sensitivity on scalp crown during bleach processing. Always apply pre-color botanical soothing barrier oil.',
        isConfidential: true,
      },
      {
        id: 'NT-08',
        date: '18 May 2026',
        author: 'Front Desk',
        type: 'Styling Preference',
        content: 'Enjoys iced almond milk latte during coloring sessions.',
      },
    ],
    photos: [
      {
        id: 'PH-05',
        date: '04 Aug 2026',
        service: 'Balayage',
        staff: 'Rohit Verma',
        type: 'Before',
        caption: 'Prior warm brassy mid-lengths before dimensional color transformation',
        consentGranted: true,
      },
      {
        id: 'PH-06',
        date: '04 Aug 2026',
        service: 'Balayage',
        staff: 'Rohit Verma',
        type: 'After',
        caption: 'Seamless champagne cool ash balayage with high-shine gloss finish',
        consentGranted: true,
      },
      {
        id: 'PH-07',
        date: '02 Jul 2026',
        service: 'Nail Art',
        staff: 'Kavita Iyer',
        type: 'After',
        caption: 'Sculpted almond gel extensions with minimalist micro-French tips',
        consentGranted: true,
      },
    ],
    consent: {
      whatsappConsent: true,
      smsConsent: true,
      emailConsent: true,
      phoneConsent: true,
      pushConsent: true,
      marketingConsent: true,
      photoConsent: true,
      consultationConsent: true,
      dateGranted: '10 Nov 2024',
      lastUpdated: '04 Aug 2026',
    },
    autoCelebrationSettings: {
      birthdayAutoSend: true,
      birthdayLeadDays: 5,
      birthdayChannel: 'whatsapp',
      anniversaryAutoSend: true,
      anniversaryLeadDays: 7,
      anniversaryChannel: 'whatsapp',
    },
  },
  {
    id: 'CL-10495',
    firstName: 'Tanvi',
    lastName: 'Rao',
    fullName: 'Tanvi Rao',
    mobile: '+91 98980 33220',
    email: 'tanvi.rao@bengaluru.in',
    gender: 'Female',
    dob: '03 Feb 1999',
    anniversary: '28 Feb 2023',
    anniversaryOccasion: 'Relationship Anniversary',
    avatarInitials: 'TR',
    avatarUrl:
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    accentColor: '#D97706',
    primaryBranch: 'Atelier Whitefield Studio',
    primaryBranchId: '22983161-1cc6-4ef3-a39f-97bc9af2cdb4',
    franchiseId: 'f2e9206f-653e-48f5-90b1-f5cca50cc92d',
    clientSince: 'Mar 2025',
    status: 'Active',
    segment: 'New Client',
    membershipTier: 'Silver Elite Member',
    activePackage: '4-Session Luxury Manicure & Pedicure Duo',
    totalVisits: 3,
    completedVisits: 3,
    cancelledVisits: 0,
    noShows: 0,
    lastVisit: '15 Jul 2026',
    lifetimeValue: 7400,
    averageVisitValue: 2466,
    walletBalance: 950,
    loyaltyPoints: 420,
    rebookingRate: 66,
    preferredStaff: 'Kavita Iyer',
    preferredServices: 'Sculpted Gel Extensions, Russian Manicure',
    preferredChannel: 'WhatsApp',
    language: 'English, Kannada',
    address: {
      line1: 'Prestige Ozone Villa 88',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560066',
      country: 'India',
    },
    household: {
      name: 'Rao Family',
      members: [
        {
          name: 'Tanvi Rao',
          relation: 'Self (Primary)',
          mobile: '+91 98980 33220',
          isPrimary: true,
        },
      ],
    },
    appointments: [
      {
        id: 'APT-910',
        date: '20 Aug 2026',
        time: '01:00 PM',
        branch: 'Atelier Whitefield Studio',
        service: 'Sculpted Gel Infill & Chrome Glaze',
        staff: 'Kavita Iyer',
        status: 'Confirmed',
        amount: 2200,
        source: 'WhatsApp Booking',
      },
      {
        id: 'APT-871',
        date: '15 Jul 2026',
        time: '02:30 PM',
        branch: 'Atelier Whitefield Studio',
        service: 'Sculpted Gel Extensions & Ombre Art',
        staff: 'Kavita Iyer',
        status: 'Completed',
        amount: 3200,
        source: 'Online Mobile App',
      },
      {
        id: 'APT-802',
        date: '10 Jun 2026',
        time: '11:00 AM',
        branch: 'Atelier Whitefield Studio',
        service: 'Signature Precision Cut & Conditioning Mask',
        staff: 'Manish Rawat',
        status: 'Completed',
        amount: 2000,
        source: 'Front Desk Phone',
      },
    ],
    serviceHistory: [
      {
        id: 'SH-14',
        date: '15 Jul 2026',
        branch: 'Atelier Whitefield Studio',
        service: 'Sculpted Gel Extensions & Ombre Art',
        staff: 'Kavita Iyer',
        amount: 3200,
        packageOrMembership: 'Package Session 1/4',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-15',
        date: '10 Jun 2026',
        branch: 'Atelier Whitefield Studio',
        service: 'Signature Precision Cut & Conditioning Mask',
        staff: 'Manish Rawat',
        amount: 2000,
        packageOrMembership: 'Silver Tier 5% Off',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-16',
        date: '02 May 2026',
        branch: 'Atelier Whitefield Studio',
        service: 'Deluxe Spa Pedicure with Paraffin Treatment',
        staff: 'Kavita Iyer',
        amount: 2200,
        packageOrMembership: 'A la carte',
        rating: 5,
        status: 'Completed',
      },
    ],
    packages: [
      {
        id: 'PKG-06',
        name: '4-Session Luxury Manicure & Pedicure Duo',
        purchaseDate: '15 Jul 2026',
        expiryDate: '15 Jan 2027',
        sessionsPurchased: 4,
        sessionsUsed: 1,
        sessionsRemaining: 3,
        packageValue: 8800,
        remainingValue: 6600,
        status: 'Active',
      },
    ],
    loyaltyTransactions: [
      {
        id: 'TX-14',
        date: '15 Jul 2026',
        type: 'Earned',
        description: 'Nail Extension Loyalty Points',
        amountOrPoints: '+160 Pts',
        balance: '420 Pts',
      },
      {
        id: 'TX-15',
        date: '15 Jul 2026',
        type: 'Wallet Topup',
        description: 'UPI Topup at Salon Kiosk',
        amountOrPoints: '+₹2,000',
        balance: '₹2,000',
      },
      {
        id: 'TX-16',
        date: '15 Jul 2026',
        type: 'Service Debit',
        description: 'Chrome Glaze Upgrade Charge',
        amountOrPoints: '-₹1,050',
        balance: '₹950',
      },
    ],
    feedbacks: [
      {
        id: 'FB-08',
        date: '15 Jul 2026',
        service: 'Gel Extensions & Ombre',
        branch: 'Atelier Whitefield Studio',
        rating: 5,
        npsType: 'Promoter',
        feedback: 'Kavita has the neatest cuticle work and the ombre transition is pristine.',
      },
    ],
    notes: [
      {
        id: 'NT-09',
        date: '15 Jul 2026',
        author: 'Kavita Iyer',
        type: 'Styling Preference',
        content:
          'Prefers medium almond nail shape. No manual nipping on cuticles — use diamond flame e-file bit only.',
      },
    ],
    photos: [
      {
        id: 'PH-08',
        date: '15 Jul 2026',
        service: 'Nail Extensions',
        staff: 'Kavita Iyer',
        type: 'Before',
        caption: 'Natural nail plate prep and dehydrated cuticle cleanup',
        consentGranted: true,
      },
      {
        id: 'PH-09',
        date: '15 Jul 2026',
        service: 'Nail Extensions',
        staff: 'Kavita Iyer',
        type: 'After',
        caption: 'Finished French baby-boomer ombre with glossy top coat',
        consentGranted: true,
      },
    ],
    consent: {
      whatsappConsent: true,
      smsConsent: true,
      emailConsent: true,
      phoneConsent: true,
      pushConsent: true,
      marketingConsent: true,
      photoConsent: true,
      consultationConsent: true,
      dateGranted: '12 Mar 2025',
      lastUpdated: '15 Jul 2026',
    },
    autoCelebrationSettings: {
      birthdayAutoSend: true,
      birthdayLeadDays: 1,
      birthdayChannel: 'whatsapp',
      anniversaryAutoSend: true,
      anniversaryLeadDays: 3,
      anniversaryChannel: 'whatsapp',
    },
  },
  {
    id: 'CL-10496',
    firstName: 'Vikram',
    lastName: 'Rathore',
    fullName: 'Vikram Rathore',
    mobile: '+91 97840 99880',
    email: 'vikram.rathore@jaipur-heritage.in',
    gender: 'Male',
    dob: '19 Oct 1978',
    anniversary: '20 Nov 2008',
    anniversaryOccasion: 'Wedding Anniversary',
    avatarInitials: 'VR',
    avatarUrl:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    accentColor: '#7C3AED',
    primaryBranch: 'Atelier Jaipur Royal Spa',
    primaryBranchId: '6b9ce3d7-b71c-404b-bd09-cfb43af547b2',
    franchiseId: '7b2adb85-860b-43e5-b33d-6d77b2fd0b70',
    clientSince: 'Aug 2024',
    status: 'Inactive',
    segment: 'At Risk',
    membershipTier: 'Gold VIP Member',
    activePackage: '5-Session Deep Tissue Stress Relief Package',
    totalVisits: 8,
    completedVisits: 7,
    cancelledVisits: 1,
    noShows: 0,
    lastVisit: '18 Apr 2026',
    lifetimeValue: 28900,
    averageVisitValue: 3612,
    walletBalance: 2200,
    loyaltyPoints: 680,
    rebookingRate: 40,
    preferredStaff: 'Manish Rawat',
    preferredServices: 'Swedish Aromatherapy & Hot Stone Massage',
    preferredChannel: 'Phone',
    language: 'Hindi, English',
    address: {
      line1: 'C-Scheme, Ashok Nagar',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302001',
      country: 'India',
    },
    household: {
      name: 'Rathore Household',
      members: [
        {
          name: 'Vikram Rathore',
          relation: 'Self (Primary)',
          mobile: '+91 97840 99880',
          isPrimary: true,
        },
        { name: 'Sunita Rathore', relation: 'Spouse', mobile: '+91 97840 99882' },
      ],
    },
    appointments: [
      {
        id: 'APT-865',
        date: '18 Apr 2026',
        time: '04:00 PM',
        branch: 'Atelier Jaipur Royal Spa',
        service: 'Swedish Aromatherapy Deep Tissue Massage',
        staff: 'Manish Rawat',
        status: 'Completed',
        amount: 4200,
        source: 'Front Desk Phone',
      },
      {
        id: 'APT-798',
        date: '15 Mar 2026',
        time: '05:30 PM',
        branch: 'Atelier Jaipur Royal Spa',
        service: 'Royal Balinese Body Polish & Steam Bath',
        staff: 'Manish Rawat',
        status: 'Completed',
        amount: 3800,
        source: 'Front Desk Phone',
      },
    ],
    serviceHistory: [
      {
        id: 'SH-17',
        date: '18 Apr 2026',
        branch: 'Atelier Jaipur Royal Spa',
        service: 'Swedish Aromatherapy Deep Tissue Massage',
        staff: 'Manish Rawat',
        amount: 4200,
        packageOrMembership: 'Package Session 3/5',
        rating: 5,
        status: 'Completed',
      },
      {
        id: 'SH-18',
        date: '15 Mar 2026',
        branch: 'Atelier Jaipur Royal Spa',
        service: 'Royal Balinese Body Polish & Steam Bath',
        staff: 'Manish Rawat',
        amount: 3800,
        packageOrMembership: 'Gold Tier 10% Off',
        rating: 4,
        status: 'Completed',
      },
      {
        id: 'SH-19',
        date: '08 Feb 2026',
        branch: 'Atelier Jaipur Royal Spa',
        service: 'Deep Tissue Recovery Therapy',
        staff: 'Manish Rawat',
        amount: 4200,
        packageOrMembership: 'Package Session 2/5',
        rating: 5,
        status: 'Completed',
      },
    ],
    packages: [
      {
        id: 'PKG-07',
        name: '5-Session Deep Tissue Stress Relief Package',
        purchaseDate: '10 Jan 2026',
        expiryDate: '10 Jan 2027',
        sessionsPurchased: 5,
        sessionsUsed: 3,
        sessionsRemaining: 2,
        packageValue: 18500,
        remainingValue: 7400,
        status: 'Active',
      },
    ],
    loyaltyTransactions: [
      {
        id: 'TX-17',
        date: '18 Apr 2026',
        type: 'Earned',
        description: 'Spa Service Loyalty Accrual',
        amountOrPoints: '+210 Pts',
        balance: '680 Pts',
      },
      {
        id: 'TX-18',
        date: '15 Mar 2026',
        type: 'Wallet Topup',
        description: 'Concierge Cheque Deposit Reload',
        amountOrPoints: '+₹5,000',
        balance: '₹5,000',
      },
      {
        id: 'TX-19',
        date: '15 Mar 2026',
        type: 'Service Debit',
        description: 'Body Polish Treatment Checkout',
        amountOrPoints: '-₹2,800',
        balance: '₹2,200',
      },
    ],
    feedbacks: [
      {
        id: 'FB-09',
        date: '18 Apr 2026',
        service: 'Swedish Aromatherapy Massage',
        branch: 'Atelier Jaipur Royal Spa',
        rating: 5,
        npsType: 'Promoter',
        feedback:
          'Manish is an exceptional therapist who understands muscle anatomy and pressure points thoroughly.',
      },
    ],
    notes: [
      {
        id: 'NT-10',
        date: '18 Apr 2026',
        author: 'Manish Rawat',
        type: 'Medical / Allergy',
        content:
          'Chronic lower back stiffness and cervical tension from polo riding. Prefers extra firm pressure with warm Ayurvedic Mahanarayan oil.',
        isConfidential: true,
      },
      {
        id: 'NT-11',
        date: '15 Mar 2026',
        author: 'Front Desk',
        type: 'Styling Preference',
        content: 'Prefers quiet royal spa suite with sandalwood incense aroma.',
      },
    ],
    photos: [
      {
        id: 'PH-10',
        date: '18 Apr 2026',
        service: 'Spa Suite Setup',
        staff: 'Manish Rawat',
        type: 'After',
        caption: 'Private Royal Suite prepared with heated Himalayan salt stones and herbal steam',
        consentGranted: true,
      },
    ],
    consent: {
      whatsappConsent: false,
      smsConsent: true,
      emailConsent: false,
      phoneConsent: true,
      pushConsent: false,
      marketingConsent: false,
      photoConsent: true,
      consultationConsent: true,
      dateGranted: '15 Aug 2024',
      lastUpdated: '18 Apr 2026',
    },
    autoCelebrationSettings: {
      birthdayAutoSend: true,
      birthdayLeadDays: 7,
      birthdayChannel: 'sms',
      anniversaryAutoSend: true,
      anniversaryLeadDays: 14,
      anniversaryChannel: 'sms',
    },
  },
  {
    id: 'CL-10488',
    firstName: 'Kunal',
    lastName: 'Singhania',
    fullName: 'Kunal Singhania',
    mobile: '+91 98110 55440',
    email: 'kunal.singhania@delhi-tech.com',
    gender: 'Male',
    dob: '11 Jul 1994',
    anniversary: '14 Feb 2022',
    anniversaryOccasion: 'Wedding Anniversary',
    avatarInitials: 'KS',
    avatarUrl:
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    accentColor: '#3B82F6',
    primaryBranch: 'Atelier MG Road Express',
    primaryBranchId: '22983161-1cc6-4ef3-a39f-97bc9af2cdb4',
    franchiseId: 'f2e9206f-653e-48f5-90b1-f5cca50cc92d',
    clientSince: 'Feb 2025',
    status: 'Active',
    segment: 'New Client',
    membershipTier: 'Silver Elite Member',
    activePackage: "3-Session Men's Executive Styling Pass",
    totalVisits: 4,
    completedVisits: 4,
    cancelledVisits: 0,
    noShows: 0,
    lastVisit: '02 Aug 2026',
    lifetimeValue: 9200,
    averageVisitValue: 2300,
    walletBalance: 1500,
    loyaltyPoints: 320,
    rebookingRate: 75,
    preferredStaff: 'Rahul Sharma (GM)',
    preferredServices: 'Signature Precision Cut & Scalp Treatment',
    preferredChannel: 'WhatsApp',
    language: 'English, Hindi',
    address: {
      line1: 'B-10, MG Road Boulevard, Sector 14',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122001',
      country: 'India',
    },
    household: {
      name: 'Singhania Household',
      members: [
        {
          name: 'Kunal Singhania',
          relation: 'Self (Primary)',
          mobile: '+91 98110 55440',
          isPrimary: true,
        },
      ],
    },
    appointments: [
      {
        id: 'APT-928',
        date: '26 Aug 2026',
        time: '03:00 PM',
        branch: 'Atelier MG Road Express',
        service: 'Complimentary Master Hair Styling & Scalp Detox Session',
        staff: 'Rahul Sharma (GM)',
        status: 'Booked',
        amount: 0,
        source: 'Front Desk Phone',
      },
      {
        id: 'APT-879',
        date: '02 Aug 2026',
        time: '06:00 PM',
        branch: 'Atelier MG Road Express',
        service: 'Signature Precision Cut & Blowout',
        staff: 'Sameer Sheikh',
        status: 'Completed',
        amount: 1850,
        source: 'Online Mobile App',
      },
      {
        id: 'APT-815',
        date: '20 Jun 2026',
        time: '04:00 PM',
        branch: 'Atelier MG Road Express',
        service: 'Deep Cleansing Charcoal Scalp Scrub & Cut',
        staff: 'Sameer Sheikh',
        status: 'Completed',
        amount: 2400,
        source: 'Front Desk Phone',
      },
    ],
    serviceHistory: [
      {
        id: 'SH-20',
        date: '02 Aug 2026',
        branch: 'Atelier MG Road Express',
        service: 'Signature Precision Cut & Blowout',
        staff: 'Sameer Sheikh',
        amount: 1850,
        packageOrMembership: 'Package Session 1/3',
        rating: 2,
        status: 'Completed',
      },
      {
        id: 'SH-21',
        date: '20 Jun 2026',
        branch: 'Atelier MG Road Express',
        service: 'Deep Cleansing Charcoal Scalp Scrub & Cut',
        staff: 'Sameer Sheikh',
        amount: 2400,
        packageOrMembership: 'Silver Tier 5% Off',
        rating: 5,
        status: 'Completed',
      },
    ],
    packages: [
      {
        id: 'PKG-08',
        name: "3-Session Men's Executive Styling Pass",
        purchaseDate: '20 Jun 2026',
        expiryDate: '20 Dec 2026',
        sessionsPurchased: 3,
        sessionsUsed: 1,
        sessionsRemaining: 2,
        packageValue: 5500,
        remainingValue: 3666,
        status: 'Active',
      },
    ],
    loyaltyTransactions: [
      {
        id: 'TX-20',
        date: '03 Aug 2026',
        type: 'Wallet Topup',
        description: 'Customer Recovery Goodwill Credit from GM',
        amountOrPoints: '+₹500',
        balance: '₹1,500',
      },
      {
        id: 'TX-21',
        date: '02 Aug 2026',
        type: 'Earned',
        description: 'Service Reward Points',
        amountOrPoints: '+90 Pts',
        balance: '320 Pts',
      },
      {
        id: 'TX-22',
        date: '20 Jun 2026',
        type: 'Wallet Topup',
        description: 'Razorpay UPI Wallet Reload',
        amountOrPoints: '+₹1,000',
        balance: '₹1,000',
      },
    ],
    feedbacks: [
      {
        id: 'FB-10',
        date: '02 Aug 2026',
        service: 'Signature Precision Cut & Blowout',
        branch: 'Atelier MG Road Express',
        rating: 2,
        npsType: 'Detractor',
        feedback:
          'Haircut was shorter than agreed during consultation. Water temperature at shampoo basin was also too hot.',
      },
    ],
    notes: [
      {
        id: 'NT-12',
        date: '03 Aug 2026',
        author: 'Rahul Sharma (GM)',
        type: 'Billing Note',
        content:
          'Personal phone outreach by GM Rahul Sharma. Client accepted complimentary corrective styling session on 26 Aug and ₹500 goodwill wallet credit.',
        isConfidential: true,
      },
      {
        id: 'NT-13',
        date: '02 Aug 2026',
        author: 'Sameer Sheikh',
        type: 'Styling Preference',
        content:
          'Client keeps hair longer on top (at least 3.5 inches). Verify length with scissors before clipper blending.',
      },
    ],
    photos: [
      {
        id: 'PH-11',
        date: '02 Aug 2026',
        service: 'Precision Cut',
        staff: 'Sameer Sheikh',
        type: 'Before',
        caption: 'Consultation profile view before length adjustment',
        consentGranted: true,
      },
      {
        id: 'PH-12',
        date: '02 Aug 2026',
        service: 'Precision Cut',
        staff: 'Sameer Sheikh',
        type: 'After',
        caption: 'Post-cut texture profile for evaluation',
        consentGranted: true,
      },
    ],
    consent: {
      whatsappConsent: true,
      smsConsent: true,
      emailConsent: true,
      phoneConsent: true,
      pushConsent: true,
      marketingConsent: true,
      photoConsent: true,
      consultationConsent: true,
      dateGranted: '10 Feb 2025',
      lastUpdated: '03 Aug 2026',
    },
    autoCelebrationSettings: {
      birthdayAutoSend: true,
      birthdayLeadDays: 3,
      birthdayChannel: 'whatsapp',
      anniversaryAutoSend: true,
      anniversaryLeadDays: 5,
      anniversaryChannel: 'whatsapp',
    },
  },
];
